---
version: '2.1'
services:
  kubemq:
    hostname: kubemq
    image: kubemq/kubemq-community:latest
    ports:
      - 8080:8080
      - 50000:50000
      - 9090:9090
    networks:
      - kafka-network

  zookeeper:
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network

  kafka-spike:
    container_name: "kafka-spike"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    expose:
      - "8000"
    ports:
      - "8060:8000"
    networks:
      - kafka-network

  faust-spike:
    container_name: "faust-spike"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    command: ["./start-faust-app"]
    networks:
      - kafka-network

networks:
  kafka-network:
